{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e13af7a7-8411-4a40-b2ca-f432963bca07",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "from pyspark.sql import SparkSession\n",
    "from pyspark.sql.functions import *\n",
    "from pyspark import SparkContext, SparkConf\n",
    "import pyspark\n",
    "import pandas as pd\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore', category=DeprecationWarning)\n",
    "from pyspark.sql.types import StringType,TimestampType\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c94cfd21-1ccf-4082-ad45-572ade5533f9",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Setting spark.hadoop.yarn.resourcemanager.principal to hvega.externo\n"
     ]
    }
   ],
   "source": [
    "ss_name = 'Agregación de labels a contaminados'\n",
    "wg_conn = \"spark.kerberos.access.hadoopFileSystems\"\n",
    "db_conn = \"abfs://data@datalakesii.dfs.core.windows.net/\"\n",
    "\n",
    "spark = SparkSession.builder \\\n",
    "      .appName(f\"Ejecucion algoritmo {ss_name}\")  \\\n",
    "      .config(wg_conn, db_conn) \\\n",
    "      .config(\"spark.executor.memory\", \"6g\") \\\n",
    "      .config(\"spark.driver.memory\", \"12g\")\\\n",
    "      .config(\"spark.executor.cores\", \"4\") \\\n",
    "      .config(\"spark.executor.instances\", \"5\") \\\n",
    "      .config(\"spark.driver.maxResultSize\", \"12g\") \\\n",
    "      .getOrCreate()\n",
    "\n",
    "spark.sparkContext.setLogLevel(\"ERROR\")\n",
    "\n",
    "spark.conf.set(\"spark.sql.parquet.enableVectorizedReader\",\"false\")\n",
    "spark.conf.set(\"spark.sql.parquet.int96RebaseModeInRead\", \"CORRECTED\")\n",
    "spark.conf.set(\"spark.sql.parquet.int96RebaseModeInWrite\", \"CORRECTED\")\n",
    "spark.conf.set(\"spark.sql.parquet.datetimeRebaseModeInRead\", \"CORRECTED\")\n",
    "spark.conf.set(\"spark.sql.parquet.datetimeRebaseModeInWrite\", \"CORRECTED\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "207bd4c9-5b0f-4118-ad2a-062bad596921",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "                                                                                \r"
     ]
    }
   ],
   "source": [
    "df_spark = spark.read.parquet(\"abfs://data@datalakesii.dfs.core.windows.net/DatosOrigen/lr-629/propuesta_f29_comunidades/data_contaminados_with_labels\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "be81cfb3-8d56-4a53-837f-995b05736bbf",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "                                                                                \r"
     ]
    }
   ],
   "source": [
    "df_pandas = df_spark.toPandas()\n",
    "spark.stop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d84adab1-cfd3-4097-9663-6e81af999bff",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "26afb9a91b4e4dc8a9012d614054e282",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "interactive(children=(Dropdown(description='Region:', options=('8VA UNIDAD REGIONAL BIO BIO', 'SANTIAGO SUR', …"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import ipywidgets as widgets\n",
    "from IPython.display import display\n",
    "\n",
    "# Función para actualizar el gráfico basado en los inputs del usuario\n",
    "def update_graph(region):\n",
    "    filtered_df = df_pandas[df_pandas['unidad_regional'] == region]\n",
    "    plt.figure(figsize=(10, 6))\n",
    "    plt.hist(filtered_df['score'], bins=20, alpha=0.7)\n",
    "    plt.title(f'Score Distribution in {region}')\n",
    "    plt.xlabel('Score')\n",
    "    plt.ylabel('Frequency')\n",
    "    plt.show()\n",
    "\n",
    "# Crear un widget de selección para las regiones\n",
    "regions = df_pandas['unidad_regional'].unique()\n",
    "region_selector = widgets.Dropdown(\n",
    "    options=regions,\n",
    "    description='Region:',\n",
    ")\n",
    "\n",
    "# Enlazar el widget al gráfico\n",
    "widgets.interactive(update_graph, region=region_selector)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "e64895c4-a152-4a62-be31-dc82384def7a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 279, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 121, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py\", line 406, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py\", line 70, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/middleware/errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/middleware/errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/gradio/route_utils.py\", line 766, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/gradio/route_utils.py\", line 782, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/dependencies/utils.py\", line 639, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/dependencies/utils.py\", line 810, in request_body_to_args\n",
      "    fields_to_extract = get_model_fields(first_field.type_)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/_compat.py\", line 283, in get_model_fields\n",
      "    return [\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/_compat.py\", line 284, in <listcomp>\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/_compat.py\", line 109, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 266, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 144, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 286, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 104, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 908, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2025, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2104, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2186, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2182, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2085, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1029, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1058, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1378, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1038, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 558, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 279, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 121, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py\", line 406, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py\", line 70, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/middleware/errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/middleware/errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/gradio/route_utils.py\", line 766, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/gradio/route_utils.py\", line 782, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/dependencies/utils.py\", line 639, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/dependencies/utils.py\", line 810, in request_body_to_args\n",
      "    fields_to_extract = get_model_fields(first_field.type_)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/_compat.py\", line 283, in get_model_fields\n",
      "    return [\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/_compat.py\", line 284, in <listcomp>\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/_compat.py\", line 109, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 266, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 144, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 286, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 104, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 908, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2025, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2104, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2186, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2182, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2085, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1029, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1058, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1378, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1038, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 558, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 279, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 121, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py\", line 406, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py\", line 70, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/middleware/errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/middleware/errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/gradio/route_utils.py\", line 766, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/gradio/route_utils.py\", line 782, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/starlette/routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/dependencies/utils.py\", line 639, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/dependencies/utils.py\", line 810, in request_body_to_args\n",
      "    fields_to_extract = get_model_fields(first_field.type_)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/_compat.py\", line 283, in get_model_fields\n",
      "    return [\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/_compat.py\", line 284, in <listcomp>\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/fastapi/_compat.py\", line 109, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 266, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 144, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 286, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/type_adapter.py\", line 104, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 908, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2025, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2104, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2186, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2182, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 2085, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1029, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1058, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1378, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 1038, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "  File \"/home/cdsw/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py\", line 558, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type\n"
     ]
    }
   ],
   "source": [
    "#!pip install gradio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "45bcd4f4-9a7a-47bd-ad4c-11f7df020fed",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running on local URL:  http://127.0.0.1:7860\n",
      "Running on public URL: https://29c68fa0dc9478dd65.gradio.live\n",
      "\n",
      "This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"https://29c68fa0dc9478dd65.gradio.live\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import gradio as gr\n",
    "import matplotlib.pyplot as plt\n",
    "import io\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "def plot_score_distribution(region):\n",
    "    filtered_df = df_pandas[df_pandas['unidad_regional'] == region]\n",
    "    plt.figure(figsize=(10, 6))\n",
    "    plt.hist(filtered_df['score'], bins=20, alpha=0.7)\n",
    "    plt.title(f'Score Distribution in {region}')\n",
    "    plt.xlabel('Score')\n",
    "    plt.ylabel('Frequency')\n",
    "\n",
    "    # Save plot to a BytesIO object\n",
    "    img_bytes = io.BytesIO()\n",
    "    plt.savefig(img_bytes, format='png')\n",
    "    img_bytes.seek(0)\n",
    "    plt.close()\n",
    "    \n",
    "    return img_bytes.getvalue()\n",
    "\n",
    "def main():\n",
    "    regions = df_pandas['unidad_regional'].unique().tolist()  # Convertir a lista\n",
    "    # Asegurarse de que todas las opciones sean cadenas\n",
    "    regions = [str(region) for region in regions]\n",
    "    interface = gr.Interface(\n",
    "        fn=plot_score_distribution,\n",
    "        inputs=gr.Dropdown(choices=regions, label=\"Select Region\"),\n",
    "        outputs=gr.Image(type=\"bytes\")  # Cambiado a \"bytes\"\n",
    "    )\n",
    "    interface.launch(share=True)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "59f51494-b447-4ebb-bec7-077ddb16820c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
